name: Build Jar

on:
  push:
    branches:
      - workflow-building

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn -B package

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/*.jar
